=== Adrisira/LenguajeMarcas1DAM/Tema 1/Boletin2/Ejercicio.dtd
<!ELEMENT personas (persona*)>
<!ELEMENT persona (nombre*, apellidos*, nacimiento*, direcciones*)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT nacimiento EMPTY>
<!ELEMENT direcciones (direccion*)>
<!ELEMENT direccion (calle*, poblacion*, provincia*, cpostal*)>
<!ELEMENT calle (#PCDATA)>
<!ELEMENT poblacion (#PCDATA)>
<!ELEMENT provincia (#PCDATA)>
<!ELEMENT cpostal (#PCDATA)>

<!ATTLIST persona sexo CDATA #REQUIRED>
<!ATTLIST persona relacion CDATA #REQUIRED>
<!ATTLIST nacimiento dia CDATA #REQUIRED>
<!ATTLIST nacimiento mes CDATA #REQUIRED>
<!ATTLIST nacimiento anio CDATA #REQUIRED>
<!ATTLIST direccion tipo CDATA #REQUIRED>

=== Adrisira/LenguajeMarcas1DAM/Tema 1/Boletin2/Ej10.xml
<?xml version='1.0'?>
<!DOCTYPE personas SYSTEM 'Ejercicio.dtd'>
<personas>
<persona sexo='varon' relacion='jefe'>
<nombre>John</nombre>
<apellidos>Smith</apellidos>
        <nacimiento dia='21' mes='enero' anio='1969'/>
        <direcciones>
            <direccion tipo='profesional'>
                <calle>AvdaUniversidad30</calle>
                <poblacion>Leganes</poblacion>
                <provincia>Madrid</provincia>
                <cpostal>28905</cpostal>
            </direccion>
            <direccion tipo='personal'>
                <calle>Madrid30</calle>
                <poblacion>Getafe</poblacion>
                <provincia>Madrid</provincia>
                <cpostal>28901</cpostal>
            </direccion>
        </direcciones>
    </persona>
    <persona sexo='varon' relacion='familiar'>
        <nombre>John</nombre>
        <apellidos>Houston</apellidos>
        <nacimiento dia='21' mes='enero' anio='1953'/>
        <direcciones>
            <direccion tipo='profesional'>
                <calle>AvdaUniversidad10</calle>
                <poblacion>Leganes</poblacion>
                <provincia>Madrid</provincia>
                <cpostal>28905</cpostal>
            </direccion>
            <direccion tipo='personal'>
                <calle>Madrid20</calle>
                <poblacion>Getafe</poblacion>
                <provincia>Madrid</provincia>
                <cpostal>28901</cpostal>
            </direccion>
        </direcciones>
    </persona>
</personas>
