=== Adrisira/LenguajeMarcas1DAM/Tema 1/Boletin2/persona.dtd
<!ELEMENT persona (nombre, nacimiento?, direccion+, (varon|hembra))>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT nacimiento EMPTY>
<!ATTLIST nacimiento
dia CDATA #REQUIRED
mes CDATA #REQUIRED
anio CDATA #REQUIRED>
<!ELEMENT direccion (calle, poblacion, provincia, cpostal)>
<!ELEMENT calle (#PCDATA)>
<!ELEMENT poblacion (#PCDATA)>
<!ELEMENT provincia (#PCDATA)>
<!ELEMENT cpostal (#PCDATA)>
<!ELEMENT varon EMPTY>
<!ELEMENT hembra EMPTY>

=== Adrisira/LenguajeMarcas1DAM/Tema 1/Boletin2/Ejercicio9.1.xml
<?xml version='1.0'?>
<!DOCTYPE persona SYSTEM 'persona.dtd'>
<persona>
<nombre>John Smith</nombre>
<nacimiento dia='21' mes='enero' anio='1969'/>
<direccion>
<calle>Avda. Universidad, 30</calle>
<poblacion>Leganes</poblacion>
<provincia>Madrid</provincia>
<cpostal>28905</cpostal>
</direccion>
<varon/>
</persona>
