=== Adrisira/LenguajeMarcas1DAM/Tema 1/Boletin3/E4.dtd
<!ELEMENT resultados (partido+)>
<!ELEMENT partido (equipolocal, equipovisitante, goleslocal, golesvisitante)>
<!ELEMENT equipolocal (#PCDATA)>
<!ELEMENT equipovisitante (#PCDATA)>
<!ELEMENT goleslocal (#PCDATA)>
<!ELEMENT golesvisitante (#PCDATA)>

=== Adrisira/LenguajeMarcas1DAM/Tema 1/Boletin3/E4.xml
<?xml version="1.0" encoding="UTF-8"?> 
<!DOCTYPE  resultados SYSTEM "E4.dtd">

<resultados>
    <partido>
    <equipolocal>Nottingham Presa</equipolocal>
    <equipovisitante>Inter de Mitente</equipovisitante>
    <goleslocal>0</goleslocal>
    <golesvisitante>1</golesvisitante>
    </partido>
    <partido>
        <equipolocal>Vodka Juniors</equipolocal>
        <equipovisitante>Sparta da Risa</equipovisitante>
        <goleslocal>3</goleslocal>
        <golesvisitante>3</golesvisitante>
    </partido>
    <partido>
        <equipolocal>Water de MÃºnich</equipolocal>
        <equipovisitante>Esteaua es del grifo</equipovisitante>
        <goleslocal>4</goleslocal>
        <golesvisitante>2</golesvisitante>
    </partido>
</resultados>
