=== Adrisira/LenguajeMarcas1DAM/Tema 1/Actividad DTD/Ejercicio1.dtd
<!ELEMENT videoclub (peliculas)>
<!ELEMENT peliculas (pelicula+)>
<!ELEMENT pelicula (nombre, sipnosis, director?, actores, guion, tiempo, genero)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT sipnosis (#PCDATA)>
<!ELEMENT director (#PCDATA)>
<!ELEMENT actores (actor+)>
<!ELEMENT actor (#PCDATA)>
<!ELEMENT guion (#PCDATA)>
<!ELEMENT tiempo (#PCDATA)>
<!ELEMENT genero (accion | aventuras| ficcion)>
<!ELEMENT accion EMPTY>
<!ELEMENT aventuras EMPTY>
<!ELEMENT ficcion EMPTY>


<!ATTLIST pelicula id ID #REQUIRED>
<!ATTLIST pelicula unidadesDisponibles CDATA #IMPLIED>
<!ATTLIST pelicula color (si|no) #IMPLIED>
<!ATTLIST actor tpapel (principal|secundario) #REQUIRED>

=== Adrisira/LenguajeMarcas1DAM/Tema 1/Actividad DTD/Ejercicio1.xml
<?xml version='1.0'?>
<!DOCTYPE videoclub SYSTEM 'Ejercicio1.dtd'>

<videoclub>
    <peliculas>
        <pelicula id="p1" unidadesDisponibles = "2" color = "si">
            <nombre>Pepe</nombre>
            <sipnosis>Julian</sipnosis>
            <director>Pepe</director>
            <actores>
                <actor tpapel = "principal">Pepe</actor>
            </actores>
                <guion>papa</guion>
                <tiempo>mes</tiempo>
                <genero>
                    <ficcion/>
                </genero>
        </pelicula>
    </peliculas>
</videoclub>
