=== Adrisira/LenguajeMarcas1DAM/Tema 1/Examen/EjercicioDTD.dtd
<!ELEMENT gimnasio (socios, actividades)>
<!ELEMENT socios (socio+)>
<!ELEMENT socio (dni, nombre, telefono?, email*, familiares*)>
<!ELEMENT dni (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT familiares (nombre, dni)>
<!ELEMENT actividades (actividad+)>
<!ELEMENT actividad (horario, (pago | gratis))>
<!ELEMENT horario (dia, horainicio, horafin)>
<!ELEMENT pago EMPTY>
<!ELEMENT gratis EMPTY>
<!ELEMENT dia (#PCDATA)>
<!ELEMENT horainicio (#PCDATA)>
<!ELEMENT horafin (#PCDATA)>

<!ATTLIST socio id ID #REQUIRED socioreferido IDREF #IMPLIED>
<!ATTLIST familiares relacion (hijo | pareja) #REQUIRED>
<!ATTLIST familiares fechanacimiento CDATA #IMPLIED>
<!ATTLIST actividad duracion CDATA #REQUIRED>

=== Adrisira/LenguajeMarcas1DAM/Tema 1/Examen/EjercicioDTD.xml
<?xml version='1.0'?>
<!DOCTYPE gimnasio SYSTEM 'EjercicioDTD.dtd'>

<gimnasio>
    <socios>
        <socio id="p1">
            <dni>1234f</dni>
            <nombre>Pepe</nombre>
            <telefono>1234</telefono>
            <email>aaaaa@gmail.com</email>
            <familiares relacion="hijo" fechanacimiento="17/08/1998">
                <nombre>jose</nombre>
                <dni>19191991f</dni>
            </familiares>
        </socio>
        <socio id="p2" socioreferido="p1">
            <dni>1234f</dni>
            <nombre>Pepe</nombre>
            <telefono>1234</telefono>
            <email>aaaaa@gmail.com</email>
            <familiares relacion="hijo" fechanacimiento="17/08/1998">
                <nombre>jose</nombre>
                <dni>19191991f</dni>
            </familiares>
        </socio>
    </socios>
    <actividades>
        <actividad duracion="23">
            <horario>
                <dia></dia>
                <horainicio></horainicio>
                <horafin></horafin>
            </horario>
            <pago />
        </actividad>
    </actividades>
</gimnasio>
